### ISSUE TITLE
Ошибка обновления

### ISSUE THREAD

**Issue by shavkunov** [Ivan-Veselov/roulette#6]
При проверке ставки на exact_number иногда я созерцал такой интересный вывод:

```
Exception in thread "Thread-5" java.net.ProtocolException: Invalid HTTP response start line
	at ru.spbau.bachelors2015.roulette.protocol.http.HttpInputStream.parseStartLineOfResponse(HttpInputStream.kt:80)
	at ru.spbau.bachelors2015.roulette.protocol.http.HttpInputStream.readHttpResponse(HttpInputStream.kt:33)
	at ru.spbau.bachelors2015.roulette.protocol.highlevel.ClientCommunicationSocket.sendRequest(ClientCommunicationSocket.kt:162)
	at ru.spbau.bachelors2015.roulette.protocol.highlevel.ClientCommunicationSocket.send(ClientCommunicationSocket.kt:88)
	at ru.spbau.bachelors2015.roulette.client.updaters.ListUpdate.run(ListUpdate.kt:13)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-6" ru.spbau.bachelors2015.roulette.protocol.highlevel.InvalidHttpResponse
	at ru.spbau.bachelors2015.roulette.protocol.highlevel.BalanceResponse$Companion.fromHttpRepresentation(Responses.kt:171)
	at ru.spbau.bachelors2015.roulette.protocol.highlevel.ClientCommunicationSocket.send(ClientCommunicationSocket.kt:110)
	at ru.spbau.bachelors2015.roulette.client.updaters.BalanceUpdate.run(BalanceUpdate.kt:15)
	at java.lang.Thread.run(Thread.java:748)
```

Был один крупье и один игрок
Тем самым обновление статуса игры у игрока прекращалось.
Скорее всего, это проблема с моей стороны из-за гонки данных, но все равно пока непонятно, что это

Чтобы это воспроизвести, достаточно подключить игрока и крупье и начать игру

**Comment by Ivan-Veselov** [comment]
Так один игрок или два?

**Comment by shavkunov** [comment]
Один крупье
Один игрок

**Comment by shavkunov** [comment]
Да, не так написал

**Comment by Ivan-Veselov** [comment]
Сделать ClientCommunicator потокобезопасным.
